"""Setup notebook and step model

Revision ID: 06ce99bb4ea8
Revises: 
Create Date: 2024-06-10 18:55:39.933534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06ce99bb4ea8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notebook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notebook_id'), 'notebook', ['id'], unique=False)
    op.create_index(op.f('ix_notebook_name'), 'notebook', ['name'], unique=False)
    op.create_table('notebook_step',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('notebook_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['notebook_id'], ['notebook.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notebook_step_id'), 'notebook_step', ['id'], unique=False)
    op.create_index(op.f('ix_notebook_step_index'), 'notebook_step', ['index'], unique=False)
    op.create_index(op.f('ix_notebook_step_name'), 'notebook_step', ['name'], unique=False)
    op.create_index(op.f('ix_notebook_step_type'), 'notebook_step', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notebook_step_type'), table_name='notebook_step')
    op.drop_index(op.f('ix_notebook_step_name'), table_name='notebook_step')
    op.drop_index(op.f('ix_notebook_step_index'), table_name='notebook_step')
    op.drop_index(op.f('ix_notebook_step_id'), table_name='notebook_step')
    op.drop_table('notebook_step')
    op.drop_index(op.f('ix_notebook_name'), table_name='notebook')
    op.drop_index(op.f('ix_notebook_id'), table_name='notebook')
    op.drop_table('notebook')
    # ### end Alembic commands ###
